### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by faiqhassan420**

### CODE REVIEW

**Comment by mohsinali1051** [comment]
@faiqhassan420 kindly https://www.youtube.com/watch?v=Rtpu2cWz7W8&t=289s watch this video for documentation.

**Comment by faiqhassan420** [comment]
I watched this video

**Comment by mohsinali1051** [comment]
@faiqhassan420 but unfortunately, I am unable to assume you have watched that video, it would be great if you please see @mohsinali1051 NFR1 branch documentation or @muneebwaqas416 documentation.

**Comment by faiqhassan420** [comment]
Dear mohsin Ali I make a .md file and upload it on GitHub but GitHub says
to upload it on GitHub it required to review by any 1contributors.

**Comment by mohsinali1051** [comment]
Yes, I have enabled the security layer, contributors cannot push anything into the main branch without the review of contributors.

All in all, I want you to add proper spacing in your documentation and appropriate headings. The reader should not feel any difficulty in reading the documentation. That's all the community want.

**Comment by faiqhassan420** [comment]
Finally you understand. Okay I got it .

**Comment by mohsinali1051** [comment]
Great 👍.

**Comment by faiqhassan420** [comment]
Thanks sir . you always prove a helping hand for others

**Comment by mohsinali1051** [comment]
And you cannot restrict yourself from buttering.

**Pull request closed without merging**
